defaults:
  - model: vggish
  - compnode: light_memory_1_16
  - dataset: cmd3

root_dir: ${hydra:runtime.cwd}/cmd3_audio/dataset
xp_name: cmd3_logger
checkpoint: ${checkpoint}
full_checkpoint: ${hydra:runtime.cwd}/checkpoints/${checkpoint}
result_dir: ${hydra:runtime.cwd}/results/${xp_name}
feature_dir: ${root_dir}/custom_features/${xp_name}
num_epochs: 25
clip_duration: 32
augmentation: False