defaults:
  - model: vggish
  - compnode: light_memory_1_16
  - dataset: cmd3

root_dir: ${hydra:runtime.cwd}
xp_name: last_layer
# xp_name: test
# checkpoint: last.ckpt
checkpoint: val_accuracy.ckpt
full_checkpoint: ${hydra:runtime.cwd}/outputs/audio_all/checkpoints/${checkpoint}
result_dir: ${hydra:runtime.cwd}/results/audio/${xp_name}
feature_dir: ${root_dir}/custom_features/audio/${xp_name}
num_epochs: 20