defaults:
  - model: vggish
  - compnode: light_memory_1_16
  - dataset: cmd3

root_dir: ${hydra:runtime.cwd}
xp_name: cmd3_0222_All_e20
# xp_name: test
checkpoint: cmd3_0222-epoch=20-val_loss=0.00.ckpt
full_checkpoint: ${hydra:runtime.cwd}/outputs/audio/2022-02-22/Train_AllLayers/checkpoints/${checkpoint}
result_dir: ${hydra:runtime.cwd}/results/audio/${xp_name}
feature_dir: ${root_dir}/custom_features/audio/${xp_name}
num_epochs: 100
clip_duration: 32
augmentation: False