defaults:
  - model: resnet
  - compnode: light_memory_1_16
  - dataset: cmd3

root_dir: ${hydra:runtime.cwd}
xp_name: all_layer
# xp_name: test
checkpoint: val_accuracy.ckpt
# checkpoint: last.ckpt
full_checkpoint: ${hydra:runtime.cwd}/outputs/video_all/checkpoints/${checkpoint}
result_dir: ${hydra:runtime.cwd}/results/video/${xp_name}
feature_dir: ${root_dir}/custom_features/video/${xp_name}
num_epochs: 20
clip_duration: 16
augmentation: False