defaults:
  - model: resnet
  - compnode: light_memory_1_16
  - dataset: cmd3

root_dir: ${hydra:runtime.cwd}
xp_name: cmd3_video_all_0307
# xp_name: test
checkpoint: cmd3_video_all_0307-epoch=19-val_loss=0.00.ckpt
# checkpoint: last.ckpt
full_checkpoint: ${hydra:runtime.cwd}/outputs/video_all/checkpoints/${checkpoint}
result_dir: ${hydra:runtime.cwd}/results/video/${xp_name}
feature_dir: ${root_dir}/custom_features/video/${xp_name}
num_epochs: 20
clip_duration: 16
augmentation: False